Tarea 2
Automation-Testing-Junio-Julio-Agosto/Tarea_Java-2 pull request #1
Opened 2022-06-19 03:28 UTC by juandedios199012

2022-06-20 03:19 UTC, calvarioTeacher31 requested changes
métele format code a todo el proyecto

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio2.java
> +        var nombreAnimal1 = scanner.nextLine();
separar por bloques de enter

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio2.java
> +        var nombreAnimal2 = scanner.nextLine();
separar por bloques de enter

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +        var cadena6 = scanner.nextLine();
separar por bloques de enter

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio3.java
> +
espacio innecesario

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio4.java
> +        var nombre7 = scanner.nextLine();
separar por bloques de enter

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio5.java
> +            scanner = new Scanner(System.in);
el inicializar el scanner puede ir afuera del bucle

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio5.java
> +
falta cerrar scanner

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio5.java
> +                System.out.println("favor, no sea gracioso");
aea

2022-06-20 03:19 UTC, calvarioTeacher31 commented on src/Ejercicio5.java
> +
espacio innecesario

2022-06-20 04:11 UTC, juandedios199012 commented on src/Ejercicio5.java
> +            scanner = new Scanner(System.in);
https://stackoverflow.com/questions/7209110/java-util-nosuchelementexception-no-line-found

2022-06-20 04:11 UTC, juandedios199012 commented on src/Ejercicio5.java
> +
https://stackoverflow.com/questions/7209110/java-util-nosuchelementexception-no-line-found

2022-06-20 04:16 UTC, juandedios199012 commented on src/Ejercicio5.java
> +
No se puede cerrar 2 scanner solo 1 vez por eso lo puse fuera del bucle

2022-06-20 15:25 UTC, calvarioTeacher31 commented on src/Ejercicio5.java
> +
entonces no lo abras 2 veces

2022-06-20 15:25 UTC, calvarioTeacher31 approved these changes

2022-06-21 01:43 UTC, juandedios199012 commented on src/Ejercicio5.java
> +
corregido

2022-06-21 01:44 UTC, merged